/**
 * Uploads the curated demo images (database/seed/demo/image-sources.json) to
 * Cloudinary through the SAME configured client and folders the API uses for
 * owner/review uploads, then writes database/seed/demo/images.lock.json — the
 * secure URLs that 002_demo_data.sql stores in the DB (URL in DB, file in cloud).
 *
 * Idempotent: every asset has a fixed public_id and overwrite:false, so a
 * re-run returns the existing asset instead of uploading a duplicate.
 *
 * Run from backend/: npm run seed:demo:images
 */
import { readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import cloudinary from '../../src/config/cloudinary';

interface Source {
  key: string;
  group: 'exterior' | 'pool' | 'lobby' | 'restaurant' | 'room' | 'review';
  title: string;
  source: string;
  page: string;
  author: string;
  license: string;
}

interface Locked extends Source {
  url: string;
  publicId: string;
  width: number;
  height: number;
}

const DEMO_DIR = path.resolve(__dirname, '../../../database/seed/demo');
const SOURCES = path.join(DEMO_DIR, 'image-sources.json');
const LOCK = path.join(DEMO_DIR, 'images.lock.json');
const ATTRIBUTION = path.join(DEMO_DIR, 'ATTRIBUTION.md');

// Same folders as owner-hotels.service / owner-room-types.service / reviews.service.
const folderFor = (group: Source['group']) =>
  group === 'room' ? 'hotel-booking/room-types' : group === 'review' ? 'hotel-booking/reviews' : 'hotel-booking/hotels';

// Wikimedia rejects requests without a descriptive User-Agent.
const USER_AGENT = 'HotelBookingDemoSeed/1.0 (demo data loader)';

async function toDataUri(url: string): Promise<string> {
  const res = await fetch(url, { headers: { 'User-Agent': USER_AGENT }, signal: AbortSignal.timeout(30_000) });
  if (!res.ok) throw new Error(`HTTP ${res.status} for ${url}`);
  const type = res.headers.get('content-type') ?? '';
  if (!type.startsWith('image/')) throw new Error(`Not an image (${type}) for ${url}`);
  const buffer = Buffer.from(await res.arrayBuffer());
  return `data:${type.split(';')[0]};base64,${buffer.toString('base64')}`;
}

async function uploadOne(src: Source): Promise<Locked> {
  const folder = folderFor(src.group);
  const publicId = `demo-${src.key}`;
  const dataUri = await toDataUri(src.source);
  const result = await cloudinary.uploader.upload(dataUri, {
    folder,
    public_id: publicId,
    overwrite: false,
    resource_type: 'image',
    // Cap stored size: hotel galleries never render wider than this.
    transformation: [{ width: 1600, crop: 'limit' }],
    timeout: 60_000,
  });
  return { ...src, url: result.secure_url, publicId: result.public_id, width: result.width, height: result.height };
}

async function main() {
  const sources: Source[] = JSON.parse(readFileSync(SOURCES, 'utf8'));
  const previous: Locked[] = (() => {
    try {
      return JSON.parse(readFileSync(LOCK, 'utf8'));
    } catch {
      return [];
    }
  })();
  const done = new Map(previous.map((l) => [l.key, l]));
  const queue = sources.filter((s) => !done.has(s.key));
  console.log(`[demo-images] ${sources.length} sources, ${done.size} already locked, ${queue.length} to upload`);

  const failures: string[] = [];
  const CONCURRENCY = 4;
  let cursor = 0;
  await Promise.all(
    Array.from({ length: CONCURRENCY }, async () => {
      while (cursor < queue.length) {
        const src = queue[cursor++];
        try {
          const locked = await uploadOne(src);
          done.set(src.key, locked);
          console.log(`  ok   ${src.key} -> ${locked.url}`);
        } catch (err) {
          failures.push(src.key);
          console.log(`  FAIL ${src.key}: ${(err as Error).message}`);
        }
      }
    })
  );

  const ordered = sources.map((s) => done.get(s.key)).filter((l): l is Locked => Boolean(l));
  writeFileSync(LOCK, JSON.stringify(ordered, null, 2) + '\n');

  const lines = [
    '# Demo image attribution',
    '',
    'Demo/test images for the seed data, sourced from Wikimedia Commons under free licenses',
    'and re-hosted on the project Cloudinary account (`hotel-booking/*`, public_id prefix `demo-`).',
    'Generated by `backend/prisma/demo-seed/upload-images.ts` — do not edit by hand.',
    '',
    '| Key | Source | Author | License |',
    '|---|---|---|---|',
    ...ordered.map((l) => `| ${l.key} | [${l.title.replace(/\|/g, '\\|')}](${l.page}) | ${l.author.replace(/\|/g, '\\|')} | ${l.license} |`),
    '',
  ];
  writeFileSync(ATTRIBUTION, lines.join('\n'));

  console.log(`[demo-images] locked ${ordered.length}/${sources.length}${failures.length ? `, failed: ${failures.join(', ')}` : ''}`);
  if (failures.length) process.exitCode = 1;
}

main();
